Add support for keycloak secret
appuio/component-openshift4-authentication pull request #28
Opened 2021-08-19 12:40 UTC by TheBigLee

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [ ] Update the documentation.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [ ] Link this PR to related issues.

2021-08-19 12:54 UTC, corvus-ch approved these changes
Looking good. Thanks for the contribution.

2021-08-19 13:02 UTC, simu approved these changes

2021-08-19 13:39 UTC, TheBigLee commented
Added some documentation on how to upgrade to the latest version due to breaking changes.

2021-08-19 15:23 UTC, simu requested changes
Please also add the new how-to in `docs/modules/ROOT/partials/nav.adoc`, simply append

```
** xref:how-tos/upgrade-2.x-to-3.x.adoc[Upgrade from 2.x to 3.x]
```

2021-08-19 15:23 UTC, simu commented on docs/modules/ROOT/pages/how-tos/upgrade-2.x-to-3.x.adoc
> +Version 3.0 adds support to configure the OIDC secret using vault instead of manually deploying the secret on the cluster.
```suggestion
Version 3.0 adds support to configure the OIDC secret using Vault instead of having to manually deploy the secret on the cluster.
```

2021-08-19 15:23 UTC, simu commented on docs/modules/ROOT/pages/how-tos/upgrade-2.x-to-3.x.adoc
> +To upgrade to the latest version follow these steps:
```suggestion
To upgrade to version 3.x follow these steps:
```

2021-08-19 15:23 UTC, simu commented on docs/modules/ROOT/pages/how-tos/upgrade-2.x-to-3.x.adoc
> +. Put the secret in vault. For example at this location: `${cluster:tenant}/${cluster:name}/oidc/clientSecret`
```suggestion
. Put the secret in Vault.
For example at this location: `${cluster:tenant}/${cluster:name}/oidc/clientSecret`
```

2021-08-19 15:23 UTC, simu commented on docs/modules/ROOT/pages/how-tos/upgrade-2.x-to-3.x.adoc
> ++          clientSecret: '?{vaultkv:${cluster:tenant}/${cluster:name}/oidc/clientSecret}'
```suggestion
. Change the `clientSecret` parameter as follows:
+
[source,diff]
----
-clientSecret:
-  name: <name_of_the_secret>
+clientSecret: '?{vaultkv:${cluster:tenant}/${cluster:name}/oidc/clientSecret}' <1>
----
<1> Use the Vault location selected in the previous step here.
```

2021-08-23 08:20 UTC, corvus-ch approved these changes
Given the remarks from @simu got addressed, this is looking good to me.

You followed the example of the component and copied the magic to create the required secret. However, meanwhile we learned that his is a bad idea — it must be done for each and every provider. For newer stuff, we intend to give the administrator the means to configure secretes and then reference them on their own. See https://github.com/appuio/component-openshift4-ingress/issues/16 as an example. It would be nice, If you could change it to that structure (only for oidc). This would prevent us from having to do braking changes should we decide to clean up this component.

2021-09-20 15:18 UTC, ccremer commented
Closed in favor of #32

2021-09-20 15:18 UTC, closed without merging